### ISSUE TITLE
Add description for contacts-plugin

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo.github.io#217] opened 2019-11-22 19:34 UTC
The documentation should have a point for the contacts plugin description

**Comment by Lineflyer** [comment] 2019-11-28 21:41
What kind of documentation do you mean? The user guide?

**Comment by bekuno** [comment] 2019-11-29 19:09
> What kind of documentation do you mean? The user guide?

Yes.
There are some points in the FAQ, but these are not good to find.

**Comment by Lineflyer** [comment] 2020-10-26 22:04
WIP: https://manual.cgeo.org/en/contacts

**Comment by Lineflyer** [comment] 2020-11-09 21:10
Duplicate of https://github.com/cgeo/cgeo-guide/issues/6

**Closed by Lineflyer** 2020-11-09 21:10 UTC
Labels: User Guide
